### PR TITLE
Update wp-post-modal-public.css

### PR DESCRIPTION
**Pull request by Birtakimseyler**
Don't scroll top when modal opens

### CODE REVIEW

**Comment by allurewebsolutions** [comment]
@birtakimseyler Thank you for your merge request!

We do need that position:fixed because we don't want the body element to scroll when the popup is open

**Comment by birtakimseyler** [comment]
Hello @allurewebsolutions, It was very little detail but on me it was important... Thank you!

Yes I understand. But it's still working on me when I delete "position:fixed" So there's no scroll.
When I click a link and open a modal for example somewhere on bottom of the page, it scrolls on top of the site. It would be better to stay actual scrolled position as background. So I deleted it.

**Comment by allurewebsolutions** [comment]
@birtakimseyler If I remove that CSS, the body will still scroll at least on the browsers I tested on.

Are you having some issue with the scrolling to top? In the latest version of the plugin, it should scroll back to the original position after closing the modal. See: https://github.com/allurewebsolutions/wordpress-post-modal/blob/master/public/js/wp-post-modal-public.js#L117

**Comment by birtakimseyler** [comment]
@allurewebsolutions Hmm I've tested on Chrome and Firefox. It was working. After closing the modal it scrolls back. But I think it would be great to keep scroll position when modal is opened. You can also take a look on my page, why I want to keep position as a background:
http://anatolianscripts.com/ara/

Thank you for your interest.

**Comment by allurewebsolutions** [comment]
@birtakimseyler If you check on the demo site, if I remove the position: fixed, then the body still scrolls when the popup is open: https://wp-post-modal.allureprojects.com/

To test I used Chrome dev tools and added content to the page (to push some below the fold) and updated the CSS in dev tools.

**Pull request closed without merging**
